title: MIT Blueprint Learnathon Arduino Track 2020
url: "https://techx.io/arduino-track/"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
timezone: America/New_York

collections:
  lectures:
    output: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
